apiVersion: v1
kind: Service
metadata:
  name: echo3
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app3.klubinzenjera.com
spec:
  selector:
    app: echo3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
